/* Spirits 101 — deep reference for beginners learning the back bar */
const SPIRITS = [
  {
    name: "Whiskey",
    icon: "🥃",
    summary: "Grain-based distilled spirit aged in wood. The category changes dramatically by country and grain.",
    types: [
      { label: "Bourbon", body: "American, min 51% corn, aged in NEW charred oak. Sweet, vanilla, caramel. (Jim Beam, Buffalo Trace, Maker's Mark, Woodford Reserve, Knob Creek)" },
      { label: "Rye", body: "American, min 51% rye grain. Spicier, drier, peppery. Preferred for Manhattans and Sazeracs. (Rittenhouse, Bulleit Rye, Sazerac, Whistlepig)" },
      { label: "Tennessee", body: "Bourbon process + charcoal filtering (Lincoln County Process). Smoother, softer. (Jack Daniel's, George Dickel)" },
      { label: "Scotch", body: "Scottish, malted barley. Blended (Dewar's, Johnnie Walker, Chivas) is approachable; Single Malt (Glenlivet, Macallan, Laphroaig) is for sipping. Islay = smoky/peaty." },
      { label: "Irish", body: "Triple-distilled, smooth, usually unpeated. Great entry whiskey. (Jameson, Tullamore Dew, Redbreast, Bushmills)" },
      { label: "Japanese", body: "Scotch-inspired, refined, floral. (Hibiki, Yamazaki, Nikka, Suntory Toki)" },
      { label: "Canadian", body: "Typically lighter, smoother, often rye-forward. (Crown Royal, Canadian Club)" },
    ],
    tip: "Memorize which whiskey goes in which drink: Manhattan = rye, Old Fashioned = bourbon, Highball = Japanese or Scotch, Sazerac = rye, Mint Julep = bourbon.",
  },
  {
    name: "Gin",
    icon: "🌿",
    summary: "Neutral spirit re-distilled with botanicals — juniper is required. Everything else is the distiller's style.",
    types: [
      { label: "London Dry", body: "The classic. Juniper-forward, crisp, dry. (Tanqueray, Beefeater, Bombay Sapphire) — use in Martinis, Negronis, G&Ts." },
      { label: "Plymouth", body: "Softer, earthier, slightly sweeter than London Dry. Only made in Plymouth, England." },
      { label: "Old Tom", body: "Slightly sweetened, historical style. Bridge between genever and London Dry. (Hayman's, Ransom)" },
      { label: "Genever", body: "Dutch original — malty, whiskey-like. The ancestor of modern gin." },
      { label: "Contemporary / New Western", body: "Juniper present but not dominant — citrus, floral, cucumber, tea. (Hendrick's, Monkey 47, Aviation, The Botanist)" },
    ],
    tip: "If a guest says 'I don't like gin', they probably had Tanqueray. Offer Hendrick's or Aviation — very different experience.",
  },
  {
    name: "Rum",
    icon: "🏝️",
    summary: "Distilled from sugarcane (molasses or fresh juice). Color is not always about age — caramel coloring is common.",
    types: [
      { label: "White / Silver", body: "Unaged or lightly aged, filtered clear. Daiquiris, Mojitos. (Bacardi, Havana Club, Plantation 3 Stars)" },
      { label: "Gold", body: "Lightly aged, mild oak notes. Versatile. (Mount Gay Eclipse, Appleton Signature)" },
      { label: "Dark", body: "Aged longer or heavier molasses base. Bold, rich. (Gosling's Black Seal, Myers's)" },
      { label: "Aged / Añejo", body: "Sipping rum — aged years in oak. Vanilla, caramel, dried fruit. (Ron Zacapa, Diplomático, Appleton 12)" },
      { label: "Rhum Agricole", body: "French Caribbean, from fresh sugarcane juice. Grassy, funky. (Rhum Clément, Rhum JM)" },
      { label: "Overproof", body: "100+ proof. Floats, tiki drinks. (Wray & Nephew, Lemon Hart 151)" },
      { label: "Spiced", body: "Infused with spices and vanilla, usually sweetened. (Captain Morgan, Kraken)" },
    ],
    tip: "Tiki drinks often use 2-3 rums blended together — that's where the complexity comes from.",
  },
  {
    name: "Tequila & Mezcal",
    icon: "🌵",
    summary: "Agave-based spirits from Mexico. Tequila = blue Weber agave from Jalisco. Mezcal = any agave, usually smoky from roasting in pits.",
    types: [
      { label: "Blanco / Silver", body: "Unaged or briefly rested. Bright agave flavor. Use in Margaritas, Palomas. (Espolòn, Olmeca Altos, Fortaleza, Casamigos Blanco)" },
      { label: "Reposado", body: "Aged 2–12 months in oak. Softer, slight vanilla. Nice middle ground." },
      { label: "Añejo", body: "Aged 1–3 years. Smooth, whiskey-like. Sipping tequila." },
      { label: "Extra Añejo", body: "Aged 3+ years. Premium, sipping neat or on a rock." },
      { label: "Mezcal", body: "Agave roasted in earthen pits — smoky, earthy, complex. (Del Maguey, Vago, Ilegal)" },
      { label: "Cristalino", body: "Añejo filtered clear. Trendy, softer flavor." },
    ],
    tip: "'100% de agave' on the label matters. Anything less is 'mixto' — mixed with other sugars, rougher hangover.",
  },
  {
    name: "Vodka",
    icon: "❄️",
    summary: "Neutral spirit — legally must be flavorless, odorless, colorless. Subtle differences come from base material (grain, potato, corn) and filtering.",
    types: [
      { label: "Grain-based", body: "Wheat (Grey Goose, Absolut), rye (Belvedere), corn (Tito's). Slight sweetness or spice depending on grain." },
      { label: "Potato", body: "Creamier mouthfeel, slightly heavier. (Chopin, Luksusowa)" },
      { label: "Flavored", body: "Citrus, vanilla, berry, etc. Cosmos and Lemon Drops use citrus vodka traditionally." },
    ],
    tip: "Most guests can't tell top-shelf vodka from well in a mixed drink. The 'premium' usually comes through on a vodka martini or straight.",
  },
  {
    name: "Brandy & Cognac",
    icon: "🍇",
    summary: "Distilled from fruit — usually wine (grapes). Cognac is brandy from a specific region of France with strict rules.",
    types: [
      { label: "Cognac", body: "French grape brandy. Grades: VS (2+ years), VSOP (4+), XO (10+). (Hennessy, Rémy Martin, Courvoisier, Martell)" },
      { label: "Armagnac", body: "Older French grape brandy — more rustic, single-distilled. Less known, often better value." },
      { label: "American Brandy", body: "Grape-based, softer. (E&J, Korbel, Copper & Kings)" },
      { label: "Pisco", body: "South American grape brandy — Peruvian or Chilean. Bright, floral." },
      { label: "Applejack / Calvados", body: "Apple brandy. Calvados is French, applejack is American." },
    ],
    tip: "VS Cognac is fine for cocktails (Sidecar, Brandy Alexander). Save VSOP+ for sipping.",
  },
  {
    name: "Liqueurs & Modifiers",
    icon: "🍯",
    summary: "Sweetened, flavored spirits used to add dimension. These are the supporting cast — know what each does.",
    types: [
      { label: "Triple Sec / Curaçao", body: "Orange liqueur. Cointreau is the premium brand. Essential for Margaritas, Sidecars, Cosmos." },
      { label: "Grand Marnier", body: "Cognac-based orange liqueur. Richer than triple sec." },
      { label: "Campari", body: "Italian bitter aperitif, bright red. Negroni, Boulevardier, Americano." },
      { label: "Aperol", body: "Lighter, sweeter cousin of Campari. Spritzes." },
      { label: "Sweet Vermouth", body: "Italian fortified wine, herbal. Manhattans, Negronis. (Carpano Antica, Cocchi, Dolin Rouge)" },
      { label: "Dry Vermouth", body: "French fortified wine, dry and herbal. Martinis. (Dolin Dry, Noilly Prat)" },
      { label: "Maraschino", body: "Italian cherry liqueur, dry not sweet. Last Word, Aviation." },
      { label: "Chartreuse", body: "French herbal liqueur, 130 herbs. Green (110 proof, intense) or Yellow (softer)." },
      { label: "Amaro", body: "Italian bitter herbal digestif. Many styles — Averna, Montenegro, Fernet, Nonino." },
      { label: "Kahlúa", body: "Coffee liqueur. Espresso Martini, White Russian, B-52." },
      { label: "Baileys", body: "Irish cream liqueur. B-52, Mudslide." },
    ],
    tip: "Vermouth is WINE. It oxidizes. Refrigerate after opening, toss after 1-2 months. Dusty vermouth ruins a Martini.",
  },
];
