// Drink database. Each drink has:
//   name, category, spirit (primary), glass, method, garnish, ingredients[], steps[], note
// Methods: shake, stir, build, muddle+shake, muddle+build, blend
// Glasses: rocks, coupe, martini, highball, collins, mug, flute, hurricane, nick & nora, shot

const DRINKS = [
  // ── CLASSICS (know these cold) ──────────────────────────────────
  {
    name: "Old Fashioned",
    category: "Classics",
    spirit: "Whiskey",
    glass: "Rocks",
    method: "Build / Stir",
    garnish: "Orange peel (express oils)",
    ingredients: [
      { item: "Bourbon or rye", amount: "2 oz" },
      { item: "Sugar cube or simple syrup", amount: "1 tsp / 0.25 oz" },
      { item: "Angostura bitters", amount: "2–3 dashes" },
      { item: "Orange peel", amount: "1" },
    ],
    steps: [
      "Add sugar and bitters to rocks glass; muddle if using a cube.",
      "Add whiskey and a large ice cube.",
      "Stir gently 15–20 seconds.",
      "Express orange peel over drink, rub rim, drop in.",
    ],
    note: "The benchmark. If a guest asks how good your bar is, they're ordering this.",
  },
  {
    name: "Manhattan",
    category: "Classics",
    spirit: "Whiskey",
    glass: "Coupe",
    method: "Stir",
    garnish: "Brandied cherry",
    ingredients: [
      { item: "Rye whiskey", amount: "2 oz" },
      { item: "Sweet vermouth", amount: "1 oz" },
      { item: "Angostura bitters", amount: "2 dashes" },
    ],
    steps: [
      "Combine in mixing glass with ice.",
      "Stir 20–30 seconds until well chilled.",
      "Strain into chilled coupe.",
      "Garnish with cherry.",
    ],
    note: "Stirred, never shaken (all-spirit drinks stay silky when stirred).",
  },
  {
    name: "Martini (Gin)",
    category: "Classics",
    spirit: "Gin",
    glass: "Martini",
    method: "Stir",
    garnish: "Lemon twist or olive",
    ingredients: [
      { item: "London dry gin", amount: "2.5 oz" },
      { item: "Dry vermouth", amount: "0.5 oz" },
      { item: "Orange bitters (optional)", amount: "1 dash" },
    ],
    steps: [
      "Stir with ice 25–30 seconds.",
      "Strain into chilled martini glass or coupe.",
      "Garnish with twist or olive per guest preference.",
    ],
    note: "Ask: gin or vodka? Dry or wet? Olive or twist? Up or on the rocks?",
  },
  {
    name: "Negroni",
    category: "Classics",
    spirit: "Gin",
    glass: "Rocks",
    method: "Build / Stir",
    garnish: "Orange peel",
    ingredients: [
      { item: "Gin", amount: "1 oz" },
      { item: "Campari", amount: "1 oz" },
      { item: "Sweet vermouth", amount: "1 oz" },
    ],
    steps: [
      "Build over large ice cube in rocks glass.",
      "Stir briefly to combine and chill.",
      "Express orange peel, drop in.",
    ],
    note: "Equal parts — easy to remember, impossible to mess up.",
  },
  {
    name: "Daiquiri",
    category: "Classics",
    spirit: "Rum",
    glass: "Coupe",
    method: "Shake",
    garnish: "Lime wheel (optional)",
    ingredients: [
      { item: "White rum", amount: "2 oz" },
      { item: "Fresh lime juice", amount: "1 oz" },
      { item: "Simple syrup", amount: "0.75 oz" },
    ],
    steps: [
      "Shake hard with ice 10–12 seconds.",
      "Double strain into chilled coupe.",
    ],
    note: "The template for every sour. Nothing frozen — a real daiquiri is straight up.",
  },
  {
    name: "Margarita",
    category: "Classics",
    spirit: "Tequila",
    glass: "Rocks (salted rim)",
    method: "Shake",
    garnish: "Lime wheel, salt rim",
    ingredients: [
      { item: "Blanco tequila", amount: "2 oz" },
      { item: "Fresh lime juice", amount: "1 oz" },
      { item: "Triple sec / Cointreau", amount: "0.75 oz" },
      { item: "Agave syrup (optional)", amount: "0.25 oz" },
    ],
    steps: [
      "Salt half the rim with a lime wedge and kosher salt.",
      "Shake all ingredients with ice.",
      "Strain over fresh ice in salted glass.",
    ],
    note: "Always ask: rocks or frozen? Salt or no salt?",
  },
  {
    name: "Mojito",
    category: "Classics",
    spirit: "Rum",
    glass: "Highball",
    method: "Muddle + Build",
    garnish: "Mint sprig, lime wheel",
    ingredients: [
      { item: "White rum", amount: "2 oz" },
      { item: "Fresh lime juice", amount: "0.75 oz" },
      { item: "Simple syrup", amount: "0.5 oz" },
      { item: "Fresh mint", amount: "8–10 leaves" },
      { item: "Soda water", amount: "Top" },
    ],
    steps: [
      "Gently press (don't pulverize) mint with syrup in glass.",
      "Add rum and lime, fill with crushed ice.",
      "Top with soda, stir gently.",
      "Slap mint sprig, place on top.",
    ],
    note: "Bruise the mint, don't shred it — shredded mint = bitter drink.",
  },
  {
    name: "Whiskey Sour",
    category: "Classics",
    spirit: "Whiskey",
    glass: "Rocks or Coupe",
    method: "Shake",
    garnish: "Cherry + orange, or lemon peel",
    ingredients: [
      { item: "Bourbon", amount: "2 oz" },
      { item: "Fresh lemon juice", amount: "0.75 oz" },
      { item: "Simple syrup", amount: "0.75 oz" },
      { item: "Egg white (optional)", amount: "1" },
    ],
    steps: [
      "If using egg white: dry shake (no ice) 10 seconds first.",
      "Add ice, shake hard 10–12 seconds.",
      "Strain over fresh ice or into coupe.",
      "Garnish.",
    ],
    note: "Egg white gives a silky foam — optional but classic.",
  },
  {
    name: "Moscow Mule",
    category: "Classics",
    spirit: "Vodka",
    glass: "Copper Mug",
    method: "Build",
    garnish: "Lime wedge, mint",
    ingredients: [
      { item: "Vodka", amount: "2 oz" },
      { item: "Fresh lime juice", amount: "0.5 oz" },
      { item: "Ginger beer", amount: "4 oz / top" },
    ],
    steps: [
      "Fill mug with ice.",
      "Add vodka and lime, top with ginger beer.",
      "Stir briefly, garnish.",
    ],
    note: "Ginger BEER (spicy), not ginger ale (sweet).",
  },
  {
    name: "Cosmopolitan",
    category: "Classics",
    spirit: "Vodka",
    glass: "Martini",
    method: "Shake",
    garnish: "Lime wheel or flamed orange peel",
    ingredients: [
      { item: "Citrus vodka", amount: "1.5 oz" },
      { item: "Triple sec / Cointreau", amount: "0.75 oz" },
      { item: "Cranberry juice", amount: "0.75 oz" },
      { item: "Fresh lime juice", amount: "0.5 oz" },
    ],
    steps: [
      "Shake hard with ice.",
      "Double strain into chilled martini glass.",
    ],
    note: "Pink, tart, a little sweet. Shake hard to get it ice-cold.",
  },

  // ── SOURS ───────────────────────────────────────────────────────
  {
    name: "Gimlet",
    category: "Sours",
    spirit: "Gin",
    glass: "Coupe",
    method: "Shake",
    garnish: "Lime wheel",
    ingredients: [
      { item: "Gin (or vodka)", amount: "2 oz" },
      { item: "Fresh lime juice", amount: "0.75 oz" },
      { item: "Simple syrup", amount: "0.75 oz" },
    ],
    steps: [
      "Shake hard with ice.",
      "Double strain into chilled coupe.",
    ],
    note: "A daiquiri with gin. Classic, clean, lime-forward.",
  },
  {
    name: "Sidecar",
    category: "Sours",
    spirit: "Brandy",
    glass: "Coupe (sugared rim)",
    method: "Shake",
    garnish: "Orange peel, sugar rim",
    ingredients: [
      { item: "Cognac", amount: "2 oz" },
      { item: "Cointreau", amount: "0.75 oz" },
      { item: "Fresh lemon juice", amount: "0.75 oz" },
    ],
    steps: [
      "Sugar half the rim.",
      "Shake with ice, double strain into coupe.",
    ],
    note: "Template for all 'sour' style cocktails (spirit + citrus + orange liqueur).",
  },
  {
    name: "Amaretto Sour",
    category: "Sours",
    spirit: "Liqueur",
    glass: "Rocks",
    method: "Shake",
    garnish: "Cherry, orange slice",
    ingredients: [
      { item: "Amaretto", amount: "1.5 oz" },
      { item: "Bourbon (optional)", amount: "0.75 oz" },
      { item: "Fresh lemon juice", amount: "1 oz" },
      { item: "Simple syrup", amount: "0.25 oz" },
      { item: "Egg white (optional)", amount: "1" },
    ],
    steps: [
      "Dry shake if using egg white.",
      "Shake with ice, strain over fresh ice.",
    ],
    note: "Bourbon float balances amaretto's sweetness — crowd favorite.",
  },
  {
    name: "Pisco Sour",
    category: "Sours",
    spirit: "Pisco",
    glass: "Coupe",
    method: "Shake",
    garnish: "3 drops Angostura on foam",
    ingredients: [
      { item: "Pisco", amount: "2 oz" },
      { item: "Fresh lime juice", amount: "0.75 oz" },
      { item: "Simple syrup", amount: "0.75 oz" },
      { item: "Egg white", amount: "1" },
    ],
    steps: [
      "Dry shake without ice 10 seconds.",
      "Shake with ice 10 seconds.",
      "Strain into coupe, dot bitters on foam.",
    ],
    note: "Peru's national drink. The bitters on foam is the signature.",
  },
  {
    name: "Tom Collins",
    category: "Sours",
    spirit: "Gin",
    glass: "Collins",
    method: "Shake + Top",
    garnish: "Lemon wheel, cherry",
    ingredients: [
      { item: "Gin", amount: "2 oz" },
      { item: "Fresh lemon juice", amount: "1 oz" },
      { item: "Simple syrup", amount: "0.5 oz" },
      { item: "Soda water", amount: "Top" },
    ],
    steps: [
      "Shake gin, lemon, syrup with ice.",
      "Strain into collins glass with fresh ice.",
      "Top with soda, stir briefly.",
    ],
    note: "Essentially a fizzy, taller gin sour.",
  },

  // ── HIGHBALLS / LONG DRINKS ─────────────────────────────────────
  {
    name: "Gin & Tonic",
    category: "Highballs",
    spirit: "Gin",
    glass: "Highball",
    method: "Build",
    garnish: "Lime wedge (or cucumber)",
    ingredients: [
      { item: "Gin", amount: "2 oz" },
      { item: "Tonic water", amount: "4–5 oz / top" },
      { item: "Lime wedge", amount: "1" },
    ],
    steps: [
      "Fill glass with ice.",
      "Add gin, top with tonic.",
      "Squeeze lime, drop in.",
    ],
    note: "Use fresh tonic. Flat tonic = flat drink.",
  },
  {
    name: "Vodka Soda",
    category: "Highballs",
    spirit: "Vodka",
    glass: "Highball",
    method: "Build",
    garnish: "Lime wedge",
    ingredients: [
      { item: "Vodka", amount: "2 oz" },
      { item: "Soda water", amount: "Top" },
      { item: "Lime wedge", amount: "1" },
    ],
    steps: [
      "Fill with ice, add vodka, top with soda.",
      "Squeeze lime.",
    ],
    note: "The 'I'm watching my calories' drink. Know it, make it fast.",
  },
  {
    name: "Rum & Coke / Cuba Libre",
    category: "Highballs",
    spirit: "Rum",
    glass: "Highball",
    method: "Build",
    garnish: "Lime wedge",
    ingredients: [
      { item: "White or dark rum", amount: "2 oz" },
      { item: "Coca-Cola", amount: "Top" },
      { item: "Fresh lime juice", amount: "0.5 oz (for Cuba Libre)" },
    ],
    steps: [
      "Fill with ice, add rum.",
      "Top with Coke, squeeze lime.",
    ],
    note: "With lime = Cuba Libre. Without = Rum & Coke.",
  },
  {
    name: "Whiskey Ginger",
    category: "Highballs",
    spirit: "Whiskey",
    glass: "Highball",
    method: "Build",
    garnish: "Lime wedge",
    ingredients: [
      { item: "Bourbon or rye", amount: "2 oz" },
      { item: "Ginger ale", amount: "Top" },
    ],
    steps: [
      "Fill with ice, add whiskey, top with ginger ale.",
    ],
    note: "Jack & ginger is the most common order — ask brand preference.",
  },
  {
    name: "Paloma",
    category: "Highballs",
    spirit: "Tequila",
    glass: "Highball",
    method: "Build",
    garnish: "Lime wedge, salt rim (optional)",
    ingredients: [
      { item: "Blanco tequila", amount: "2 oz" },
      { item: "Fresh lime juice", amount: "0.5 oz" },
      { item: "Grapefruit soda (Jarritos/Squirt)", amount: "Top" },
      { item: "Pinch of salt", amount: "1" },
    ],
    steps: [
      "Salt the rim if desired.",
      "Build over ice, stir gently.",
    ],
    note: "More popular in Mexico than the margarita. Refreshing.",
  },
  {
    name: "Dark 'n' Stormy",
    category: "Highballs",
    spirit: "Rum",
    glass: "Highball",
    method: "Build",
    garnish: "Lime wedge",
    ingredients: [
      { item: "Dark rum (Goslings traditionally)", amount: "2 oz" },
      { item: "Ginger beer", amount: "Top" },
      { item: "Fresh lime juice", amount: "0.5 oz" },
    ],
    steps: [
      "Build ginger beer and lime over ice.",
      "Float dark rum on top.",
    ],
    note: "The float is the 'storm cloud' — don't stir too hard.",
  },
  {
    name: "Jack & Coke",
    category: "Highballs",
    spirit: "Whiskey",
    glass: "Highball",
    method: "Build",
    garnish: "Lime (optional)",
    ingredients: [
      { item: "Jack Daniel's", amount: "2 oz" },
      { item: "Coca-Cola", amount: "Top" },
    ],
    steps: [
      "Fill with ice, add Jack, top with Coke.",
    ],
    note: "The most-ordered cocktail in America. Make it fast.",
  },
  {
    name: "Highball (Japanese)",
    category: "Highballs",
    spirit: "Whiskey",
    glass: "Highball",
    method: "Build",
    garnish: "Lemon peel",
    ingredients: [
      { item: "Japanese whisky", amount: "1.5 oz" },
      { item: "Soda water (ice cold)", amount: "4 oz" },
    ],
    steps: [
      "Chill glass with ice, discard any melt.",
      "Add whisky, stir 3x.",
      "Add cold soda, stir 1x gently.",
      "Express lemon peel.",
    ],
    note: "Feels simple — technique (cold soda, minimal stirring) makes or breaks it.",
  },

  // ── TROPICAL / TIKI ─────────────────────────────────────────────
  {
    name: "Piña Colada",
    category: "Tropical",
    spirit: "Rum",
    glass: "Hurricane",
    method: "Blend",
    garnish: "Pineapple wedge, cherry",
    ingredients: [
      { item: "White rum", amount: "2 oz" },
      { item: "Coconut cream (Coco Lopez)", amount: "1.5 oz" },
      { item: "Pineapple juice", amount: "3 oz" },
    ],
    steps: [
      "Blend with 1 cup ice until smooth.",
      "Pour into hurricane glass, garnish.",
    ],
    note: "Shake-style also works (served on crushed ice) — ask the guest.",
  },
  {
    name: "Mai Tai",
    category: "Tropical",
    spirit: "Rum",
    glass: "Double Rocks",
    method: "Shake",
    garnish: "Mint, lime wheel, orchid",
    ingredients: [
      { item: "Aged rum", amount: "1 oz" },
      { item: "Dark/overproof rum (float)", amount: "0.75 oz" },
      { item: "Orange curaçao", amount: "0.5 oz" },
      { item: "Orgeat (almond syrup)", amount: "0.5 oz" },
      { item: "Fresh lime juice", amount: "1 oz" },
    ],
    steps: [
      "Shake all except dark rum with crushed ice.",
      "Pour into glass, float dark rum on top.",
      "Garnish heavily.",
    ],
    note: "Trader Vic original — not the pink fruit-punch imposter.",
  },
  {
    name: "Bay Breeze",
    category: "Tropical",
    spirit: "Vodka",
    glass: "Highball",
    method: "Build",
    garnish: "Lime wedge",
    ingredients: [
      { item: "Vodka", amount: "1.5 oz" },
      { item: "Cranberry juice", amount: "2 oz" },
      { item: "Pineapple juice", amount: "2 oz" },
    ],
    steps: [
      "Build over ice, stir.",
    ],
    note: "Swap cranberry for grapefruit = Sea Breeze.",
  },
  {
    name: "Sea Breeze",
    category: "Tropical",
    spirit: "Vodka",
    glass: "Highball",
    method: "Build",
    garnish: "Lime wedge",
    ingredients: [
      { item: "Vodka", amount: "1.5 oz" },
      { item: "Cranberry juice", amount: "3 oz" },
      { item: "Grapefruit juice", amount: "1.5 oz" },
    ],
    steps: [
      "Build over ice, stir.",
    ],
    note: "Pink, tart — a beach staple.",
  },
  {
    name: "Long Island Iced Tea",
    category: "Tropical",
    spirit: "Mixed",
    glass: "Collins",
    method: "Shake + Top",
    garnish: "Lemon wedge",
    ingredients: [
      { item: "Vodka", amount: "0.5 oz" },
      { item: "Gin", amount: "0.5 oz" },
      { item: "White rum", amount: "0.5 oz" },
      { item: "Blanco tequila", amount: "0.5 oz" },
      { item: "Triple sec", amount: "0.5 oz" },
      { item: "Fresh lemon juice", amount: "0.75 oz" },
      { item: "Simple syrup", amount: "0.5 oz" },
      { item: "Cola", amount: "Splash / top" },
    ],
    steps: [
      "Shake spirits, lemon, syrup with ice.",
      "Strain into collins glass with fresh ice.",
      "Top with a splash of cola for color.",
    ],
    note: "Strong. If someone orders two in a row, cut them off.",
  },

  // ── BUBBLY / BRUNCH ─────────────────────────────────────────────
  {
    name: "Mimosa",
    category: "Bubbly",
    spirit: "Wine",
    glass: "Flute",
    method: "Build",
    garnish: "Orange slice (optional)",
    ingredients: [
      { item: "Champagne / prosecco", amount: "3 oz" },
      { item: "Fresh orange juice", amount: "3 oz" },
    ],
    steps: [
      "Add OJ to flute, top with sparkling wine.",
      "Do NOT stir (kills bubbles).",
    ],
    note: "Champagne first or juice first? Juice first prevents overflow.",
  },
  {
    name: "Bellini",
    category: "Bubbly",
    spirit: "Wine",
    glass: "Flute",
    method: "Build",
    garnish: "None",
    ingredients: [
      { item: "White peach purée", amount: "2 oz" },
      { item: "Prosecco", amount: "4 oz" },
    ],
    steps: [
      "Add purée to flute, top slowly with prosecco.",
    ],
    note: "Italian classic. Real peach purée — not peach schnapps.",
  },
  {
    name: "Aperol Spritz",
    category: "Bubbly",
    spirit: "Liqueur",
    glass: "Wine Glass",
    method: "Build",
    garnish: "Orange slice",
    ingredients: [
      { item: "Aperol", amount: "3 oz" },
      { item: "Prosecco", amount: "3 oz" },
      { item: "Soda water", amount: "Splash" },
    ],
    steps: [
      "Fill wine glass with ice.",
      "Build in order: prosecco, Aperol, soda splash.",
      "Garnish with orange.",
    ],
    note: "3-2-1 ratio (prosecco-Aperol-soda) is the official IBA formula.",
  },
  {
    name: "French 75",
    category: "Bubbly",
    spirit: "Gin",
    glass: "Flute",
    method: "Shake + Top",
    garnish: "Lemon twist",
    ingredients: [
      { item: "Gin", amount: "1 oz" },
      { item: "Fresh lemon juice", amount: "0.5 oz" },
      { item: "Simple syrup", amount: "0.5 oz" },
      { item: "Champagne", amount: "Top" },
    ],
    steps: [
      "Shake gin, lemon, syrup with ice.",
      "Strain into flute, top with champagne.",
    ],
    note: "Named after a WWI artillery piece — packs a similar punch.",
  },
  {
    name: "Kir Royale",
    category: "Bubbly",
    spirit: "Wine",
    glass: "Flute",
    method: "Build",
    garnish: "Lemon twist",
    ingredients: [
      { item: "Crème de cassis", amount: "0.5 oz" },
      { item: "Champagne", amount: "Top" },
    ],
    steps: [
      "Pour cassis into flute, top with champagne.",
    ],
    note: "Swap champagne for white wine = regular Kir.",
  },

  // ── WHISKEY-FORWARD ─────────────────────────────────────────────
  {
    name: "Boulevardier",
    category: "Whiskey",
    spirit: "Whiskey",
    glass: "Rocks",
    method: "Stir",
    garnish: "Orange peel",
    ingredients: [
      { item: "Bourbon or rye", amount: "1.5 oz" },
      { item: "Campari", amount: "1 oz" },
      { item: "Sweet vermouth", amount: "1 oz" },
    ],
    steps: [
      "Stir with ice until chilled.",
      "Strain over large cube.",
      "Express orange peel.",
    ],
    note: "A Negroni with whiskey instead of gin. Richer, warmer.",
  },
  {
    name: "Sazerac",
    category: "Whiskey",
    spirit: "Whiskey",
    glass: "Rocks (no ice)",
    method: "Stir",
    garnish: "Lemon peel",
    ingredients: [
      { item: "Rye whiskey", amount: "2 oz" },
      { item: "Sugar cube or simple", amount: "1 / 0.25 oz" },
      { item: "Peychaud's bitters", amount: "3 dashes" },
      { item: "Absinthe (rinse)", amount: "~0.25 oz" },
    ],
    steps: [
      "Rinse rocks glass with absinthe; discard excess.",
      "Stir rye, sugar, bitters with ice in mixing glass.",
      "Strain into absinthe-rinsed glass (no ice).",
      "Express lemon peel, discard peel.",
    ],
    note: "New Orleans classic. The absinthe rinse is the whole point.",
  },
  {
    name: "Mint Julep",
    category: "Whiskey",
    spirit: "Whiskey",
    glass: "Julep Cup",
    method: "Muddle + Build",
    garnish: "Mint bouquet",
    ingredients: [
      { item: "Bourbon", amount: "2.5 oz" },
      { item: "Simple syrup", amount: "0.5 oz" },
      { item: "Fresh mint", amount: "8–10 leaves" },
    ],
    steps: [
      "Gently muddle mint with syrup in cup.",
      "Fill with crushed ice, add bourbon.",
      "Swizzle until cup frosts.",
      "Top with more crushed ice, huge mint garnish.",
    ],
    note: "Kentucky Derby drink. Frost on the cup = you did it right.",
  },
  {
    name: "Rusty Nail",
    category: "Whiskey",
    spirit: "Whiskey",
    glass: "Rocks",
    method: "Build",
    garnish: "Lemon peel (optional)",
    ingredients: [
      { item: "Scotch whisky", amount: "1.5 oz" },
      { item: "Drambuie", amount: "0.75 oz" },
    ],
    steps: [
      "Build over large cube, stir briefly.",
    ],
    note: "Two ingredients, nothing fresh — old-school order.",
  },
  {
    name: "Irish Coffee",
    category: "Whiskey",
    spirit: "Whiskey",
    glass: "Mug",
    method: "Build",
    garnish: "Lightly whipped cream",
    ingredients: [
      { item: "Irish whiskey", amount: "1.5 oz" },
      { item: "Hot coffee", amount: "4 oz" },
      { item: "Brown sugar", amount: "1 tsp" },
      { item: "Lightly whipped cream", amount: "Float" },
    ],
    steps: [
      "Warm mug with hot water, dump.",
      "Add sugar, coffee, whiskey; stir.",
      "Float cream over the back of a spoon — drink through it.",
    ],
    note: "Cream should float, not sink. Don't over-whip it.",
  },
  {
    name: "Hot Toddy",
    category: "Whiskey",
    spirit: "Whiskey",
    glass: "Mug",
    method: "Build",
    garnish: "Lemon wheel, cinnamon stick",
    ingredients: [
      { item: "Bourbon or Scotch", amount: "1.5 oz" },
      { item: "Honey", amount: "1 tsp" },
      { item: "Fresh lemon juice", amount: "0.5 oz" },
      { item: "Hot water", amount: "4 oz" },
    ],
    steps: [
      "Stir honey into hot water until dissolved.",
      "Add whiskey and lemon.",
      "Garnish.",
    ],
    note: "'Sick drink' — guests order it when they feel a cold coming on.",
  },

  // ── DESSERT / COFFEE ────────────────────────────────────────────
  {
    name: "Espresso Martini",
    category: "Dessert",
    spirit: "Vodka",
    glass: "Martini / Coupe",
    method: "Shake",
    garnish: "3 coffee beans",
    ingredients: [
      { item: "Vodka", amount: "1.5 oz" },
      { item: "Coffee liqueur (Kahlúa)", amount: "0.5 oz" },
      { item: "Fresh espresso", amount: "1 oz" },
      { item: "Simple syrup", amount: "0.25 oz" },
    ],
    steps: [
      "Shake HARD with ice — long and aggressive gets the foam.",
      "Double strain into chilled glass.",
      "Float 3 beans on foam.",
    ],
    note: "Fresh espresso only. Hard shake is everything — weak shake = no foam.",
  },
  {
    name: "White Russian",
    category: "Dessert",
    spirit: "Vodka",
    glass: "Rocks",
    method: "Build",
    garnish: "None",
    ingredients: [
      { item: "Vodka", amount: "2 oz" },
      { item: "Coffee liqueur (Kahlúa)", amount: "1 oz" },
      { item: "Heavy cream", amount: "1 oz" },
    ],
    steps: [
      "Build vodka and Kahlúa over ice.",
      "Float cream on top; guest stirs.",
    ],
    note: "The Dude abides.",
  },
  {
    name: "Black Russian",
    category: "Dessert",
    spirit: "Vodka",
    glass: "Rocks",
    method: "Build",
    garnish: "None",
    ingredients: [
      { item: "Vodka", amount: "2 oz" },
      { item: "Coffee liqueur", amount: "1 oz" },
    ],
    steps: [
      "Build over ice, stir briefly.",
    ],
    note: "White Russian minus the cream.",
  },
  {
    name: "Brandy Alexander",
    category: "Dessert",
    spirit: "Brandy",
    glass: "Coupe",
    method: "Shake",
    garnish: "Grated nutmeg",
    ingredients: [
      { item: "Cognac", amount: "1 oz" },
      { item: "Crème de cacao (dark)", amount: "1 oz" },
      { item: "Heavy cream", amount: "1 oz" },
    ],
    steps: [
      "Shake with ice.",
      "Double strain into coupe.",
      "Grate nutmeg on top.",
    ],
    note: "Chocolatey, creamy — dessert in a glass.",
  },
  {
    name: "Grasshopper",
    category: "Dessert",
    spirit: "Liqueur",
    glass: "Coupe",
    method: "Shake",
    garnish: "Mint leaf",
    ingredients: [
      { item: "Green crème de menthe", amount: "1 oz" },
      { item: "Crème de cacao (white)", amount: "1 oz" },
      { item: "Heavy cream", amount: "1 oz" },
    ],
    steps: [
      "Shake with ice, double strain.",
    ],
    note: "Mint chocolate chip as a drink.",
  },
  {
    name: "Mudslide",
    category: "Dessert",
    spirit: "Vodka",
    glass: "Hurricane",
    method: "Blend",
    garnish: "Chocolate syrup swirl, whipped cream",
    ingredients: [
      { item: "Vodka", amount: "1 oz" },
      { item: "Kahlúa", amount: "1 oz" },
      { item: "Baileys Irish Cream", amount: "1 oz" },
      { item: "Vanilla ice cream or cream", amount: "2 oz" },
    ],
    steps: [
      "Line glass with chocolate syrup.",
      "Blend until smooth.",
      "Top with whipped cream.",
    ],
    note: "Dessert — usually a poolside/vacation order.",
  },

  // ── MODERN CLASSICS ─────────────────────────────────────────────
  {
    name: "Penicillin",
    category: "Modern",
    spirit: "Whiskey",
    glass: "Rocks",
    method: "Shake",
    garnish: "Candied ginger",
    ingredients: [
      { item: "Blended Scotch", amount: "2 oz" },
      { item: "Fresh lemon juice", amount: "0.75 oz" },
      { item: "Honey-ginger syrup", amount: "0.75 oz" },
      { item: "Islay Scotch (float)", amount: "0.25 oz" },
    ],
    steps: [
      "Shake everything except Islay with ice.",
      "Strain over large cube.",
      "Float smoky Islay on top.",
    ],
    note: "Modern classic — the smoky float is the signature.",
  },
  {
    name: "Paper Plane",
    category: "Modern",
    spirit: "Whiskey",
    glass: "Coupe",
    method: "Shake",
    garnish: "None",
    ingredients: [
      { item: "Bourbon", amount: "0.75 oz" },
      { item: "Aperol", amount: "0.75 oz" },
      { item: "Amaro Nonino", amount: "0.75 oz" },
      { item: "Fresh lemon juice", amount: "0.75 oz" },
    ],
    steps: [
      "Shake with ice.",
      "Double strain into coupe.",
    ],
    note: "Equal parts — easy to remember, delicious.",
  },
  {
    name: "Last Word",
    category: "Modern",
    spirit: "Gin",
    glass: "Coupe",
    method: "Shake",
    garnish: "Cherry (optional)",
    ingredients: [
      { item: "Gin", amount: "0.75 oz" },
      { item: "Green Chartreuse", amount: "0.75 oz" },
      { item: "Maraschino liqueur", amount: "0.75 oz" },
      { item: "Fresh lime juice", amount: "0.75 oz" },
    ],
    steps: [
      "Shake with ice, double strain.",
    ],
    note: "Equal parts. Chartreuse dominates — an acquired taste, but classic.",
  },
  {
    name: "Bramble",
    category: "Modern",
    spirit: "Gin",
    glass: "Rocks",
    method: "Shake + Drizzle",
    garnish: "Blackberry, lemon wheel",
    ingredients: [
      { item: "Gin", amount: "2 oz" },
      { item: "Fresh lemon juice", amount: "1 oz" },
      { item: "Simple syrup", amount: "0.5 oz" },
      { item: "Crème de mûre (blackberry)", amount: "0.5 oz" },
    ],
    steps: [
      "Shake gin, lemon, syrup with ice.",
      "Strain over crushed ice.",
      "Drizzle crème de mûre over top for 'bleeding' effect.",
    ],
    note: "Visual drink — the drizzle bleeds through the crushed ice.",
  },
  {
    name: "Moscow Mule (Kentucky Mule)",
    category: "Modern",
    spirit: "Whiskey",
    glass: "Copper Mug",
    method: "Build",
    garnish: "Lime wedge, mint",
    ingredients: [
      { item: "Bourbon", amount: "2 oz" },
      { item: "Fresh lime juice", amount: "0.5 oz" },
      { item: "Ginger beer", amount: "Top" },
    ],
    steps: [
      "Build over ice in copper mug.",
    ],
    note: "Swap vodka for bourbon = Kentucky Mule. Same template, different spirit.",
  },

  // ── SHOTS ───────────────────────────────────────────────────────
  {
    name: "Lemon Drop",
    category: "Shots",
    spirit: "Vodka",
    glass: "Shot",
    method: "Shake",
    garnish: "Sugared rim, lemon wedge",
    ingredients: [
      { item: "Citron vodka", amount: "1 oz" },
      { item: "Triple sec", amount: "0.5 oz" },
      { item: "Fresh lemon juice", amount: "0.5 oz" },
    ],
    steps: [
      "Sugar the rim of the shot glass.",
      "Shake with ice, strain into shot.",
    ],
    note: "Bite the lemon wedge after — tradition.",
  },
  {
    name: "Kamikaze",
    category: "Shots",
    spirit: "Vodka",
    glass: "Shot",
    method: "Shake",
    garnish: "None",
    ingredients: [
      { item: "Vodka", amount: "0.5 oz" },
      { item: "Triple sec", amount: "0.5 oz" },
      { item: "Fresh lime juice", amount: "0.5 oz" },
    ],
    steps: [
      "Shake with ice, strain into shot glass.",
    ],
    note: "Equal parts. Tart, strong, fast.",
  },
  {
    name: "B-52",
    category: "Shots",
    spirit: "Liqueur",
    glass: "Shot",
    method: "Layer",
    garnish: "None",
    ingredients: [
      { item: "Kahlúa", amount: "0.5 oz (bottom)" },
      { item: "Baileys Irish Cream", amount: "0.5 oz (middle)" },
      { item: "Grand Marnier", amount: "0.5 oz (top)" },
    ],
    steps: [
      "Pour Kahlúa into shot glass.",
      "Layer Baileys over the back of a spoon.",
      "Layer Grand Marnier on top the same way.",
    ],
    note: "Layered shot. Pour SLOWLY over the curve of a bar spoon.",
  },
  {
    name: "Tequila Shot",
    category: "Shots",
    spirit: "Tequila",
    glass: "Shot",
    method: "Pour",
    garnish: "Salt, lime wedge",
    ingredients: [
      { item: "Blanco tequila", amount: "1.5 oz" },
      { item: "Kosher salt", amount: "1 pinch" },
      { item: "Lime wedge", amount: "1" },
    ],
    steps: [
      "Lick hand, salt it.",
      "Lick salt, shoot tequila, bite lime.",
    ],
    note: "Lick, slam, suck. Higher-end tequila is sipped, not shot.",
  },
  {
    name: "Washington Apple",
    category: "Shots",
    spirit: "Whiskey",
    glass: "Shot",
    method: "Shake",
    garnish: "None",
    ingredients: [
      { item: "Crown Royal", amount: "0.5 oz" },
      { item: "Sour apple schnapps", amount: "0.5 oz" },
      { item: "Cranberry juice", amount: "0.5 oz" },
    ],
    steps: [
      "Shake with ice, strain into shot.",
    ],
    note: "Tastes like apple juice, hits like whiskey.",
  },
  {
    name: "Fireball Shot",
    category: "Shots",
    spirit: "Whiskey",
    glass: "Shot",
    method: "Pour",
    garnish: "None",
    ingredients: [
      { item: "Fireball cinnamon whisky", amount: "1.5 oz" },
    ],
    steps: [
      "Pour chilled into shot glass.",
    ],
    note: "Most-ordered shot in America. Keep a bottle in the well.",
  },
];

const TECHNIQUES = [
  {
    name: "Jigger / Measuring",
    body: "A jigger is your two-sided measuring cup (usually 1 oz / 0.5 oz or 1.5 oz / 0.75 oz). Fill it to the BRIM — not halfway. Free-pouring looks cool but you will over-pour 75% of the time as a new bartender. Use the jigger until the ratios are muscle memory.",
  },
  {
    name: "Shake",
    body: "For drinks with citrus, egg, dairy, or juice. Fill shaker with ice, seal tight, shake HARD for 10–12 seconds — until the tin frosts over and you can't hold it comfortably. Weak shakes = weak drinks. Strain immediately — don't let it sit.",
  },
  {
    name: "Stir",
    body: "For all-spirit drinks (Martini, Manhattan, Negroni, Old Fashioned). Stirring chills and dilutes without aerating — keeps the drink silky and clear. Stir in a mixing glass with plenty of ice for 20–30 seconds. Bar spoon touches the inside of the glass; don't whip it.",
  },
  {
    name: "Build",
    body: "Make the drink directly in the serving glass. Used for highballs (G&T, Jack & Coke, Mojito). Fill with ice first, then pour ingredients. Heaviest/least-important last (e.g., soda) to preserve fizz.",
  },
  {
    name: "Muddle",
    body: "Press herbs or fruit to release flavor — don't pulverize. For mint: a gentle press/twist just to break the oils. For fruit: firmer press. Bruising mint too hard makes it bitter.",
  },
  {
    name: "Strain",
    body: "Single strain (Hawthorne strainer) for drinks served over ice. Double strain (Hawthorne + fine mesh) for drinks served 'up' or with herbs/pulp — keeps the drink crystal clear.",
  },
  {
    name: "Dry Shake",
    body: "Shake WITHOUT ice first, then again WITH ice. Used for egg white drinks (Whiskey Sour, Pisco Sour, Ramos Fizz) to build a thick foam. Skip the dry shake and you get no foam.",
  },
  {
    name: "Express a Peel",
    body: "Hold a citrus peel skin-side-down over the drink, pinch it to spray oils across the surface. Then rub it on the rim. The oils on the surface are the whole point — it's not just a garnish.",
  },
  {
    name: "Rim the Glass",
    body: "Wet the rim with a citrus wedge (or water), then press into salt/sugar on a plate. Only rim HALF the glass — lets the guest drink from either side.",
  },
  {
    name: "Float / Layer",
    body: "Pour slowly over the back of a bar spoon so the liquid spreads across the surface instead of sinking. Used for dark-rum floats on Dark 'n' Stormy, cream on Irish Coffee, layered shots (B-52). Heaviest liquids on the bottom.",
  },
  {
    name: "Ice Matters",
    body: "Big cubes melt slowly — use for spirit-forward drinks (Old Fashioned, Negroni). Small cubes or crushed ice dilute fast and are great for tropical drinks (Mojito, Mint Julep). Never reuse ice from a shaker in the serving glass — it's already cracked and will over-dilute.",
  },
  {
    name: "Common Ratios to Memorize",
    body: "Sour template: 2 spirit / 0.75 citrus / 0.75 sweet. Manhattan/Negroni template: 2/1/1 or equal parts. Highball: 2 spirit, top with mixer. Once these three are in your head you can improvise most orders.",
  },
  {
    name: "Reading the Guest",
    body: "When in doubt: ask. 'Rocks or up?' 'Salt or no salt?' 'Any preference on gin/vodka/whiskey?' It's not weakness — it's service. Guests would rather answer one question than get the wrong drink.",
  },
];

